Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/5/2024
Var
// Seção de Declarações das variáveis 
nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite seu nome: ")
leia(nome)

escreva("Bom dia " + nome + ", estamos estudando algioritmos!")

Fimalgoritmo