Algoritmo "enquanto"

Var
   num, n1, n2, i: inteiro
   //enquanto repete em forma de um teste lógico

Inicio
   escreva("Escreva um número para o final da contagem: ")
   leia(n1)
   num:=1
   enquanto (num<=n1) faca
      //enquanto o num for menor ou igual ao número que o
      //usúario digitar ele vai repetir o loop
      escreva(num)
      num:=num+1
      //após escrever ele vai incrementar + 1
      timer(100)
   fimenquanto


Fimalgoritmo