Algoritmo "área do triângulo"

Var
base, altura: real
nome: caractere
area: real

Inicio
escreva("Boa noite!, qual seu nome? ")
leia(nome)
escreva("Olá ",nome,", informe o comprimento da base do triângulo para calcularmos a área ")
leia(base)
escreva("Certo ",nome,", informe a altura do triângulo")
leia(altura)
area:=base*altura/2
escreva(nome,", a área desse triângulo é",area,"cm² ^_^")

Fimalgoritmo