Algoritmo "quadrado do número"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/5/2024
Var
// Seção de Declarações das variáveis 
num, total: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva um número: ")
leia(num)
total:=num*num
escreva("O quadrado do número que você digitou é: ", total)

Fimalgoritmo